
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/movietrailer?characterEncoding=utf-8&useSSL=false
  #  打印sql语句
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /movietrailer
  port: 8081